# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 15:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', posts.models.LowerCaseCharField(max_length=50)),
                ('country', posts.models.LowerCaseCharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StarredJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='starredjobs',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='starredjobs',
            name='job',
        ),
        migrations.RemoveField(
            model_name='starredjobs',
            name='user',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], default=1),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='city',
            field=posts.models.LowerCaseCharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='country',
            field=posts.models.LowerCaseCharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='StarredJobs',
        ),
        migrations.AddField(
            model_name='starredjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_id', to='posts.JobPost'),
        ),
        migrations.AddField(
            model_name='starredjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_job', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='starredjob',
            unique_together=set([('job', 'user')]),
        ),
    ]
