# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_userprofile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
