# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160724_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='jobpost_id',
            new_name='job_id',
        ),
        migrations.AlterField(
            model_name='starredjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobpost_id', to='posts.JobPost'),
        ),
    ]
