# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_userprofile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='token',
            new_name='credential',
        ),
    ]
