# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160724_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='employer',
            field=models.CharField(default='System', max_length=50),
            preserve_default=False,
        ),
    ]
