# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160818_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='view_counter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
